name: Notion Notes Revision

on:
  schedule:
    # 8:00 AM & 3:00 PM HKT -> 00:00 & 07:00 UTC
    - cron: '18 0,7 * * *'
  workflow_dispatch:

jobs:
  run-notion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Notion Notes Revision
        run: npm run notion
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
